//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace podkraduli_beta6
{
    using System;
    using System.Collections.Generic;
    
    public partial class basket_podkradulya
    {
        public int Id { get; set; }
        public int podkradulya_Id { get; set; }
        public int basket_Id { get; set; }
    
        public virtual basket basket { get; set; }
        public virtual podkradulya podkradulya { get; set; }
    }
}
